name: fidelyo
description: "A new Flutter project."
publish_to: 'none' # Prevents accidental publication to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.1.0
  firebase_core: ^3.7.0
  cloud_firestore: ^5.4.5
  firebase_storage: ^12.3.5
  firebase_messaging: ^15.1.4
  firebase_auth: ^5.3.2
  http: ^1.2.2
  google_sign_in: ^6.2.2
  awesome_dialog: ^3.2.1
  cloud_functions: ^5.1.5
  image_picker: ^1.1.2
  cloudinary: ^1.2.0
  cloudinary_sdk: ^5.0.0+1
  image_cropper: ^8.0.2
  image: ^4.0.15
  geocoding: ^3.0.0
  qr_flutter: ^4.1.0
  qr: ^3.0.2
  mobile_scanner: ^6.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/ic_f/res/drawable-xxhdpi/ic_f.png"

flutter:
  uses-material-design: true

  assets:
    - assets/LOGO.png
    - assets/logo final fideliyo sans background 3.png
    - assets/Second_page.png
    - assets/slogon 1.png
    - assets/welcome to fideliyo 1.png
